### ISSUE TITLE
Remove Zrythm code or add a compatible license

### ISSUE THREAD

**Issue by alex-tee** [mgood7123/AAudioTrack#1]
Hi, it has come to my attention that you are using my code while violating its license terms. Eg.
`AAudioTrack2/src/main/cpp/zrythm/engine.h`

this code is licensed under the GNU APLv3+ (you can find its terms here <http://www.gnu.org/licenses/agpl-3.0.en.html>) it is a copyright violation to publish your software using my code without a compatible license, so please either remove the code or add an appropriate license to your repository

**Comment by mgood7123** [comment]
Removed in https://github.com/mgood7123/AAudioTrack/commit/3066a0f8c47abbb5597a28f78ad37a9b5fec3a94

**Comment by alex-tee** [comment]
thanks!
